version: '3.8'
services:
  front:
    build:
      context: .
      dockerfile: ./docker/local/node/Dockerfile
    container_name: front
    volumes:
      - .:/app
    ports:
      - '80:3000'
    depends_on:
      - redis
  redis:
    build:
      context: .
      dockerfile: ./docker/local/redis/Dockerfile
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
volumes:
    redis-data:
        driver: local
